git:
  targetRevision: main

stage: pro

network: mainnet

domain: beta.explorer.cardano.org

cf-explorer-infra:
  enabled: false

cf-ledger-sync:
  enabled: true
  values:
    git:
      targetRevision: "infra-develop"
    useLocalCardanoNode: true
    localCardanoNode:
      enabled: true
      volumeSize: 200Gi
      network: "mainnet"
      image:
        repository: ghcr.io/blinklabs-io/cardano-node
        tag: 8.9.0-1-amd64
      tolerations:
        - key: "role"
          operator: "Equal"
          value: "cardano-node"
          effect: "PreferNoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node.kubernetes.io/role
                    operator: In
                    values:
                      - cardano-node
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: node.kubernetes.io/role
                    operator: In
                    values:
                      - cardano-node
    indexer:
      enabled: true
      replicaCount: 0
      image:
        repository: "pro.registry.gitlab.metadata.dev.cf-deployments.org/base-infrastructure/docker-registry/cf-ledger-sync"
        tag: "bca5fd6-9109622755"
    aggregation:
      enabled: true
      replicaCount: 0
      image:
        repository: "pro.registry.gitlab.metadata.dev.cf-deployments.org/base-infrastructure/docker-registry/cf-ledger-sync-aggregation"
        tag: "bca5fd6-9109622755"
      postgres:
        dbSchema: mainnet
      store:
        account:
          history_cleanup_enabled: "false"
        executor:
          enable_parallel_processing: "true"
          use_virtual_thread_for_event_processing: "true"
          use_virtual_thread_for_batch_processing: "true"
          block_processing_threads: "4"


cf-explorer:
  enabled: true
  values:
    ingressDomains:
      - name: cloudfront
        domain: beta.explorer.cardano.org
      - name: global-lb
        domain: pro.cf-explorer-mainnet.global.beta.explorer.cardano.org
      - name: eu-west-1-lb
        domain: pro.cf-explorer-mainnet.eu-west-1.beta.explorer.cardano.org
      - name: us-east-1-lb
        domain: pro.cf-explorer-mainnet.us-east-1.beta.explorer.cardano.org
    explorerApi:
      enabled: false
      image:
        tag: "1.3.0"
      postgres:
        secret:
          hostKey: POSTGRES_READ_ONLY_HOST
      redis:
        mode: managed-standalone
        standalone:
          useSsl: "true"
      kafka:
        useSsl: "true"
        bootstrapServersSecret:
          name: infra-secrets
      tokenLogoEndpoint: https://pro-cf-explorer-token-logos.s3.eu-west-1.amazonaws.com/
      swagger:
        enabled: false
    explorerRewardsApi:
      enabled: false
      image:
        tag: "1.3.0"
    explorerAuthentication:
      enabled: true
      replicas: 1
      image:
#        tag: "0.5.0-SNAPSHOT-sanchonet-PR123"
        tag: "v0.1.15-15-g99eb9d0"
      redis:
        mode: managed-standalone
        standalone:
          useSsl: "true"
      emailFrom: "admin@beta.explorer.cardano.org"
      emailFromName: "Cardano Foundation - Explorer"
      keycloakServerUrl: "https://keycloak.pro.cf-explorer-mainnet.eu-west-1.beta.explorer.cardano.org"
    explorerFrontEnd:
      enabled: true
      image:
        tag: "1.3.0-PR3427-f3d85b2-9168883423"
      reactAppSanchonetAppUrl: "https://sanchonet.beta.explorer.cardano.org"
      reactAppPreProdAppUrl: "https://preprod.beta.explorer.cardano.org"
      reactAppPreviewAppUrl:  "https://preview.beta.explorer.cardano.org"
      reactAppMainnetAppUrl: "https://beta.explorer.cardano.org"
      reactAppAuthUrl: "https://auth-api.pro.cf-explorer-mainnet.eu-west-1.beta.explorer.cardano.org/api/v1"
      # temporary
      reactAppApiUrl: "https://api.pro.cf-explorer-mainnet.eu-west-1.beta.explorer.cardano.org/api/v1"
      reactAppWsUrl: "wss://api.pro.cf-explorer-mainnet.eu-west-1.beta.explorer.cardano.org/ws"
    crawler:
      enabled: false
    consumer:
      enabled: false
    consumerSchedules:
      enabled: false
      image:
        tag: "1.3.1"
      redis:
        mode: managed-standalone
        standalone:
          useSsl: "true"
      kafka:
        useSsl: "true"
        bootstrapServersSecret:
          name: infra-secrets
      tokenLogoEndpoint: https://pro-cf-explorer-token-logos.s3.eu-west-1.amazonaws.com/
    keycloak:
      enabled: true
      image:
        tag: 0.1.15-SNAPSHOT
      setupImage:
        tag: 0.1.15-SNAPSHOT
      hostname: keycloak.pro.cf-explorer-mainnet.eu-west-1.beta.explorer.cardano.org
      frontendDomainPublicUrl: https://beta.explorer.cardano.org
      webOrigin: https://beta.explorer.cardano.org
      redirectUri: https://beta.explorer.cardano.org/*
      forwardEventUrl: https://beta.explorer.cardano.org/api/v1/user/role-mapping

# Ada Handle Parameters
adahandle-resolver:
  enabled: true
  values:
    springProfiles: mainnet,postgres
    image:
      tag: "0.1.3"

kube-prometheus-stack:
  enabled: true
  version: 58.0.0

argo-cd:
  server:
    ingress:
      hosts:
        - argocd.pro.cf-explorer-mainnet.eu-west-1.beta.explorer.cardano.org
