git:
  targetRevision: main

stage: pro

network: preprod

domain: preprod.beta.explorer.cardano.org

cf-explorer-infra:
  enabled: true
  postgresql:
    enabled: false
  kafka:
    dbSize: 20Gi

cf-ledger-sync:
  enabled: true
  values:
    git:
      targetRevision: "infra-develop"
    useLocalCardanoNode: true
    localCardanoNode:
      enabled: true
      volumeSize: 20Gi
      network: "preprod"
      image:
        repository: ghcr.io/intersectmbo/cardano-node
        tag: 8.9.0
    indexer:
      enabled: true
      replicaCount: 0
      image:
        repository: "pro.registry.gitlab.metadata.dev.cf-deployments.org/base-infrastructure/docker-registry/cf-ledger-sync"
        tag: "bca5fd6-9109622755"
    aggregation:
      enabled: true
      replicaCount: 0
      image:
        repository: "pro.registry.gitlab.metadata.dev.cf-deployments.org/base-infrastructure/docker-registry/cf-ledger-sync-aggregation"
        tag: "bca5fd6-9109622755"
      postgres:
        dbSchema: preprod
      store:
        account:
          history_cleanup_enabled: "false"
        executor:
          enable_parallel_processing: "false"


cf-explorer:
  enabled: true
  values:
    ingressDomains:
      - name: cloudfront
        domain: preprod.beta.explorer.cardano.org
      - name: global-lb
        domain: pro.cf-explorer-preprod.global.beta.explorer.cardano.org
      - name: eu-west-1-lb
        domain: pro.cf-explorer-preprod.eu-west-1.beta.explorer.cardano.org
      - name: us-east-1-lb
        domain: pro.cf-explorer-preprod.us-east-1.beta.explorer.cardano.org
    explorerApi:
      enabled: false
      image:
        tag: "1.3.0"
      postgres:
        secret:
          hostKey: POSTGRES_READ_ONLY_HOST
      tokenLogoEndpoint: https://pro-cf-explorer-token-logos.s3.eu-west-1.amazonaws.com/
      swagger:
        enabled: false
    explorerRewardsApi:
      enabled: false
      image:
        tag: "1.3.0"
    explorerAuthentication:
      enabled: true
      replicas: 1
      image:
        tag: "0.5.0-SNAPSHOT-sanchonet-PR123"
      emailFrom: "admin@beta.explorer.cardano.org"
      emailFromName: "Cardano Foundation - Explorer"
      keycloakServerUrl: "https://keycloak.pro.cf-explorer-preprod.eu-west-1.beta.explorer.cardano.org"
    explorerFrontEnd:
      enabled: true
      image:
        tag: "1.3.0-PR3427-f3d85b2-9168883423"
      reactAppSanchonetAppUrl: "https://sanchonet.beta.explorer.cardano.org"
      reactAppPreProdAppUrl: "https://preprod.beta.explorer.cardano.org"
      reactAppPreviewAppUrl:  "https://preview.beta.explorer.cardano.org"
      reactAppMainnetAppUrl: "https://beta.explorer.cardano.org"
      reactAppAuthUrl: "https://auth-api.pro.cf-explorer-preprod.eu-west-1.beta.explorer.cardano.org/api/v1"
      # temporary
      reactAppApiUrl: "https://api.pro.cf-explorer-preprod.eu-west-1.beta.explorer.cardano.org/api/v1"
      reactAppWsUrl: "wss://api.pro.cf-explorer-preprod.eu-west-1.beta.explorer.cardano.org/ws"
    crawler:
      enabled: false
    consumer:
      enabled: false
    consumerSchedules:
      enabled: false
      image:
        tag: "1.3.1"
      tokenLogoEndpoint: https://pro-cf-explorer-token-logos.s3.eu-west-1.amazonaws.com/
    keycloak:
      enabled: true
      image:
        tag: 0.1.15-SNAPSHOT
      setupImage:
        tag: 0.1.15-SNAPSHOT
      hostname: keycloak.pro.cf-explorer-preprod.eu-west-1.beta.explorer.cardano.org
      frontendDomainPublicUrl: https://preprod.beta.explorer.cardano.org
      webOrigin: https://preprod.beta.explorer.cardano.org
      redirectUri: https://preprod.beta.explorer.cardano.org/*
      forwardEventUrl: https://preprod.beta.explorer.cardano.org/api/v1/user/role-mapping

# Ada Handle Parameters
adahandle-resolver:
  enabled: true
  values:
    springProfiles: preprod,postgres
    image:
      tag: "0.1.3"

kube-prometheus-stack:
  enabled: true
  version: 58.0.0

argo-cd:
  server:
    ingress:
      hosts:
        - argocd.pro.cf-explorer-preprod.eu-west-1.beta.explorer.cardano.org
